name: wellbeingu
description: An educational platform for mental health and nutrition education.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  # firebase_auth_platform_interface: ^6.11.0
  # State Management
  provider: ^6.1.1
  
  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  lottie: ^2.7.0
  
  # Charts and Visualization
  fl_chart: ^0.65.0
  
  # Utils
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  
  # Animations
  flutter_animate: ^4.4.0
  confetti: ^0.7.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/