// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUpr2pOIKFBxUUOAjiVkrBpaAgqKs17TQ',
    appId: '1:392014929017:web:6ac118d016746afbc848a8',
    messagingSenderId: '392014929017',
    projectId: 'well-being-u',
    authDomain: 'well-being-u.firebaseapp.com',
    storageBucket: 'well-being-u.firebasestorage.app',
    measurementId: 'G-4YR798W0LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi_OI399UiRemQgYaMXwpydIkDpR1dEFc',
    appId: '1:392014929017:android:4634c28892f10b05c848a8',
    messagingSenderId: '392014929017',
    projectId: 'well-being-u',
    storageBucket: 'well-being-u.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYf1cVNl5Bcnhdz2Ht07Mq_GhGbXBgSYY',
    appId: '1:392014929017:ios:aba4ab1362a1dabac848a8',
    messagingSenderId: '392014929017',
    projectId: 'well-being-u',
    storageBucket: 'well-being-u.firebasestorage.app',
    iosBundleId: 'com.example.wellbeingu2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYf1cVNl5Bcnhdz2Ht07Mq_GhGbXBgSYY',
    appId: '1:392014929017:ios:aba4ab1362a1dabac848a8',
    messagingSenderId: '392014929017',
    projectId: 'well-being-u',
    storageBucket: 'well-being-u.firebasestorage.app',
    iosBundleId: 'com.example.wellbeingu2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUpr2pOIKFBxUUOAjiVkrBpaAgqKs17TQ',
    appId: '1:392014929017:web:892e73715ea30330c848a8',
    messagingSenderId: '392014929017',
    projectId: 'well-being-u',
    authDomain: 'well-being-u.firebaseapp.com',
    storageBucket: 'well-being-u.firebasestorage.app',
    measurementId: 'G-TKYK4PPPB5',
  );
}
